spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:framework;DB_CLOSE_DELAY=-1}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USER:sa}
    password: ${DB_PASS:}
  sql:
    init:
      mode: always

framework:
  cron:
    erp-poll:
      cron: "0 */5 * * * ?"
